CREATE TABLE ${AUDIT_SEMA_ADI}.REVINFO (REV INT8 NOT NULL, REVTSTMP INT8, PRIMARY KEY (REV));
CREATE SEQUENCE ${SEMA_ADI}.HIBERNATE_SEQUENCE;

CREATE TABLE ${SEMA_ADI}.USER (ID INT8 NOT NULL, BIO VARCHAR(4000), EMAIL VARCHAR(100), FIRST_NAME VARCHAR(100), GENDER VARCHAR(10), LAST_NAME VARCHAR(50), LOCATION VARCHAR(4000), PASSWORD VARCHAR(100), PHONE VARCHAR(20), ROLE VARCHAR(20), TITLE VARCHAR(50), VERSIYON INT8 NOT NULL, WEBSITE VARCHAR(20), PRIMARY KEY (ID));
CREATE TABLE ${AUDIT_SEMA_ADI}.USER_AUD (ID INT8 NOT NULL, ID_REVINFO INT4 NOT NULL, REV_TYPE INT2, BIO VARCHAR(4000), EMAIL VARCHAR(100), FIRST_NAME VARCHAR(100), GENDER VARCHAR(10), LAST_NAME VARCHAR(50), LOCATION VARCHAR(4000), PASSWORD VARCHAR(100), PHONE VARCHAR(20), ROLE VARCHAR(20), TITLE VARCHAR(50), WEBSITE VARCHAR(20), PRIMARY KEY (ID, ID_REVINFO));
ALTER TABLE ${AUDIT_SEMA_ADI}.USER_AUD ADD CONSTRAINT FK_JJFBELI1E0I5MF8Q9THX2N5IV FOREIGN KEY (ID_REVINFO) REFERENCES ${AUDIT_SEMA_ADI}.REVINFO;
CREATE SEQUENCE ${SEMA_ADI}.USER_ID_SEQ;


CREATE TABLE ${SEMA_ADI}.USER_TOKEN (ID INT8 NOT NULL, EXPIRATION_MINUTES INT8, STATE VARCHAR(255), TOKEN VARCHAR(50), TOKEN_REQEST_TIME TIMESTAMP, VERSIYON INT8 NOT NULL, ID_USER INT8, PRIMARY KEY (ID));
CREATE TABLE ${AUDIT_SEMA_ADI}.USER_TOKEN_AUD (ID INT8 NOT NULL, ID_REVINFO INT4 NOT NULL, REV_TYPE INT2, EXPIRATION_MINUTES INT8, STATE VARCHAR(255), TOKEN VARCHAR(50), TOKEN_REQEST_TIME TIMESTAMP, ID_USER INT8, PRIMARY KEY (ID, ID_REVINFO));
CREATE INDEX IX_USER_TOKEN_USER ON ${SEMA_ADI}.USER_TOKEN (ID_USER);
ALTER TABLE ${SEMA_ADI}.USER_TOKEN ADD CONSTRAINT FK_USER_TOKEN_USER FOREIGN KEY (ID_USER) REFERENCES ${SEMA_ADI}.USER;
ALTER TABLE ${AUDIT_SEMA_ADI}.USER_TOKEN_AUD ADD CONSTRAINT FK_16XKPXKIOBWYHE5YKK2FQS0RF FOREIGN KEY (ID_REVINFO) REFERENCES ${AUDIT_SEMA_ADI}.REVINFO;
CREATE SEQUENCE ${SEMA_ADI}.USER_TOKEN_ID_SEQ;